### ISSUE TITLE
Proposed changes

### ISSUE THREAD

**Issue by mlpzaq9998** [danjulio/tCam#1]
core can use esp32-s3 with full usb support
Add lepton2 2.5 support

**Comment by danjulio** [comment]
Thank you for the suggestions.

ESP32-S3 is very exciting chip and I will use it in the future.  However built-in USB port is very cool but cannot exist alone on a dev board because the code driving it can be deleted.  You see that in Espressif's boards - two USB connectors (native and traditional USB-UART chip connected to HW serial).  A board with a single native USB port is probably best for a dedicated device that isn't expected to have code overwritten.  I'm still trying to figure out what I would do with S3.

I'd like to provide Lepton 2/2.5 support but it would require significant changes in all code bases - having to do with resolution and spotmeter mapping - so it is a big deal, plus I don't have either core so unfortunately it's probably pretty low on the realistic priority list.  Sorry about that.
