### ISSUE TITLE
Desktop-App Fedora user

### ISSUE THREAD

**Issue by lambcutlet** [danjulio/tCam#6]
Hi,
Hardware, tcam-mini rev2, lepton 3.0.
I have just downloaded the latest Desktop-App Linux64_3_1_0. Running on Fedora37.
The latest firmware has been uploaded to tcam-mini.
Stream, the image for streaming is not present until i change window focus by clicking on another app. The image briefly appears and disappears. The graph on the right is active and changes when passing your hand over the lepton.
Get is similar but the image persists after changing window focus.
Tried the same setup with Windows and all works. 
Is there anything i need to install in Linux for the image to appear when streaming?

**Comment by danjulio** [comment]
I'm sorry you're having trouble.  Unfortunately debugging issues on Linux is very hard because of limited visibility into the mounds of software between my app and your display plus all the variation in the Linux ecosystem.  It's probably a mismatch between the Linux libraries Xojo tested with when they created the release I used to compile the program for Linux and the libraries on your Fedora 37 system.

What I can offer is to try to build you a version of the app using the latest Xojo release and see if that changes things any.

**Comment by lambcutlet** [comment]
Hi Dan, 
That would be great. I'd happily test it.
Thank for the very fast response.

**Comment by lambcutlet** [comment]
The problem may be related to Wayland. Switching over to Xorg and streaming is now visible, however S, M1, M2, M3, M4 buttons don't seem to have a function or at least don't seem to action anything. FFC does work. 
Also no temperature value appears in the area above the streaming window. I see RAW at the bottom of the colour scale.  Is this to do with using a Lepton 3.0?
fps updates at about 8.8fps.

**Comment by danjulio** [comment]
I don't think Xojo tests with Wayland.   But I'll still try to build a test version with the latest release.  Might take a day or two.

The Lepton 3.0 does not generate radiometric data so all functions related to that, including the spot meter and markers, are disabled in the application.  The "RAW" indicator indicates this is just raw data from the bolometer that the app is scaling and colorizing.  Answering this issue makes me realize I never tested what happens with the graph.  It might be completely bonkers.

FPS of 8.8 is the maximum the Lepton is capable of so that's good.

**Comment by lambcutlet** [comment]
Looking at the Xojo forums it does appear that it doesn't play nice with Wayland.
Thanks for the clarity on S, M1, etc.
Switching from RAW to AGC doesn't change the S, M1, etc. button functions either. I get it, the Lepton 3.0 is not radiometric.
OK I'll wait in anticipation to test the latest Xojo version. But at least I know your program works in Xorg which i can live with if Xojo is still not happy.

**Comment by danjulio** [comment]
Yes, it seems Wayland isn't supported.  I guess a completely different rendering model than old-school X11.  There must be some backward compatibility support but perhaps it has some issues.

https://documentation.xojo.com/resources/system_requirements_for_current_release.html

Enclosed is a build using Xojo 2022 Release 4.  I don't expect it to work for you but you can check it out. 

[tcam_linux86_3_1_1.zip](https://github.com/danjulio/tCam/files/10809605/tcam_linux86_3_1_1.zip)

**Comment by lambcutlet** [comment]
Hi, I tested the code on Wayland and it behaves in the same manner as before.
Thankyou for trying.
You may close this issue and I'll wait until Xojo catches up with Wayland. Some time in the future :).
